android.defaultConfig {
    minSdkVersion Math.max(minSdkVersion?.apiLevel ?: 15, 23)
}
configurations.all {
    resolutionStrategy {
        force "org.jetbrains.kotlin:kotlin-stdlib:1.8.0"
        force "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0"
        force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0"
    }
}
repositories {
    google()
    mavenCentral()
    mavenLocal()
    jcenter()
}

dependencies {
    implementation 'com.unity3d.ads-mediation:mediation-sdk:9.0.0' 
}